### ISSUE TITLE
Package explorer is only partly visible

### ISSUE THREAD

**Issue by rmllr** [rmllr/jqa-dashboard#12]
The package explorer used in the structure and hotspots view is only partly visible. However, it should use the available space. If it is possible with a manageable effort, a horizontal and vertikal scrollbar should be added.

![issue12](https://user-images.githubusercontent.com/31067731/50221877-de3c9200-0396-11e9-9abe-0971572afc42.jpg)

**Comment by tmewes** [comment]
Hi @rmllr! This issue should have been resolved in #13. You can test the customization and merge into the master branch if it fits. :)

**Comment by rmllr** [comment]
It works perfect now! Thank you.
