### ISSUE TITLE
Activate production build in dockerfile of dashboard

### ISSUE THREAD

**Issue by rmllr** [rmllr/jqa-dashboard#15]
At the moment the development build is used for the docker image of the dashboard.

> Compiled successfully!
> You can now view @coreui/coreui-free-react-admin-template in the browser.
>   Local:            http://localhost:3000/
>   On Your Network:  http://XXX.XXX.XXX.XXX:3000/
> Note that the development build is not optimized.
> To create a production build, use npm run build.

Please change it to production build.

**Comment by tmewes** [comment]
@rmllr The production build should now be served when running the docker image. Please test and merge my fix to master if everything works fine. :)

**Comment by rmllr** [comment]
@tmewes Thanks for developing the enhancement. To my mind, it would be an additional improvement if you reference the existing environment variable named PORT in the dockerfile. Currently, it is a hard coded 3000.

What do you think?

**Comment by tmewes** [comment]
@rmllr Good idea. I have adapted the Dockerfile and the README accordingly. Please note that the call to 'docker run' has changed slightly so that Docker can successfully access the variables.
