### ISSUE TITLE
Beginners problem collection

### ISSUE THREAD

**Issue by ascheman** [rmllr/jqa-dashboard#18]
I have reported several small issues in the Neo4j community forum: https://community.neo4j.com/t/how-to-get-started-with-jqa-dashboard/6568

**Comment by jexp** [comment]
Thanks a lot Gerd for reporting these UX issues. Good ones that you caught early.

The server connection is done via the binary bolt driver, which connects on 7687 
the Neo4j Browser runs on the http port on 7474.

**Comment by ascheman** [comment]
Thanks, Michael. It would be great if the setup information could become part of the README.

I hope you (or one of the other maintainers) will also find time to look into the other issues? I was using https://github.com/dukecon/dukecon_server for jQA - there is a profile `jqa` to prepare the database. If desired I could also try to reproduce some of the other errors with screen shots (which I could not attach to the community post).

**Comment by rmllr** [comment]
Thanks for reporting the issues and for the hint concerning Neo4j.

I will try to reproduce them with the dukecon_server and answer you asap.

**Comment by rmllr** [comment]
Gerd, you have found some important issues. Here are my suggestions how to solve them.

**How to use your own database?**

As Michael already stated, we use the bolt driver to connect to the Neo4j database. You can find the default settings in the `.env` file in the dashboard's project root. They can either be changed in the file or during runtime on the settings page. I have included this information in the [readme](https://github.com/softvis-research/jqa-dashboard#prerequisites). Entering the http protocol will be disabled in future (see issue #19). 

**How to see any "dashboard"?**

Before using the dashboard the extracted data has to be prepared with some [concepts](http://buschmais.github.io/jqassistant/doc/1.6.0/#_concepts). These concepts are stored in the folder `jqa-dashboard/data/jqassistant`. Just copy this folder in the root of your project and execute `mvn jqassistant:analyze` with `-P jqa` in your case after you have scanned your project. I have included this information in the [readme](https://github.com/softvis-research/jqa-dashboard#prerequisites) as well.

You will get the visualizations in the section quality management to work (static code analysis and test coverage) if you include the appropriate jqa-plugins for [spotbugs](https://github.com/kontext-e/jqassistant-plugins/tree/master/spotbugs) and [jacoco](https://github.com/kontext-e/jqassistant-plugins/tree/master/jacoco) for the scan.

**What does the off-Button mean?**

With the toggles you can turn the expert mode on and off. If it is turned on the corresponding cypher query fetching the data for the table or visualization appears and can be edited.
