### ISSUE TITLE
Restrict database connection to bolt protocol

### ISSUE THREAD

**Issue by rmllr** [rmllr/jqa-dashboard#19]
It should only be possible to use the bolt protocol (no http) to connect to the Neo4j database. At least the .env file and the AbstractDashboardComponent have to be changed.

**Comment by tmewes** [comment]
@rmllr Now only the bolt protocol can be used in the dashboard. Please try again anyway and merge my fix to master if everything works fine. :)

**Comment by rmllr** [comment]
Everything works as expected. However, the label "URL" on the settings page is not correct anymore and might confuse users.

The following things should be done to fix this:
- Change the label "URL" on the settings page into "IP"
- Change the help text "Since the dashboard uses the Bolt protocol, the prefix "bolt://" is automatically added to the entered URL. Default: localhost" on the settings page into "The dashboard uses the bolt protocol to connect to the database. Please ensure that the Neo4j bolt connector is enabled. Default: localhost" 
- Change the env variable name REACT_APP_NEO4J_URL into REACT_APP_NEO4J_IP
- Check if other changes are necessary
