### ISSUE TITLE
Layout problems with Latest 20 commits

### ISSUE THREAD

**Issue by DirkMahler** [rmllr/jqa-dashboard#27]
The "latest 20 commits "escapes" from its surrounding container if "Rows" (i.e. page size) is set to a value higher than 10:

![grafik](https://user-images.githubusercontent.com/437925/58326314-bb724600-7e2c-11e9-9312-c8459bc24c64.png)

A scrollbar should be allowed in this case.

Furthermore it might be a bit confusing for non-expert-mode users that the view is named "Latest 20 commits" but more than 20 rows can be set as page size.

**Comment by tmewes** [comment]
Hi @DirkMahler,

thank you for creating this issue. Your are completely right. I just fixed the height of the box and set the maximum of the rows picker to 20.

Best regards
Tino
