### ISSUE TITLE
Idea: Expert mode

### ISSUE THREAD

**Issue by feststelltaste** [rmllr/jqa-dashboard#4]
### Context
Currently, the existing cypher queries for the visualizations are all hard-coded. It would be great if experts (people that know how cypher works) could manipulate those queries directly on the dashboard (on their own risk :-) ).

### Idea
Introduce "expert mode" for each visualization section:

1. Add a switch that, when activated, shows a text field with the cypher query that is executed for the visualization
1. Add an execute button next to the text field that can fire the cypher query against the Neo4j database
1. Update the visualization with the results of the executed query

**Comment by feststelltaste** [comment]
Did a dependency analysis with the PetClinic project (based on the "Subdomain" labels). Looks great so far and does exactly what is needed! Thx! Keep on the great work!

![grafik](https://user-images.githubusercontent.com/1470822/48317859-9177d580-e5f8-11e8-9620-cc296f6ff3dc.png)

**Comment by tmewes** [comment]
Thank you very much for your early feedback! I'll let you know when the feature is completely done. :)

**Comment by tmewes** [comment]
The feature has been successfully completed now. :)

**Comment by feststelltaste** [comment]
Hey great! Thanks! Will use it with plenty of different projects and provide feedback!
